permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: check
jobs:
  fmt:
    runs-on: ubuntu-latest
    name: stable / fmt
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: cargo fmt --check
        run: cargo fmt --check
  clippy:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / clippy
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: create env
        run: mv .env.example .env
      - name: start docker stack
        run: docker compose -f contrib/compose.yaml up -d
      - name: install sqlx
        run: cargo install sqlx-cli
      - name: run migrations
        run: cargo sqlx migrate run
      - name: install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: cargo clippy
        uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-check'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: stop docker stack
        run: docker compose -f contrib/compose.yaml down -v
  doc:
    runs-on: ubuntu-latest
    name: nightly / doc
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: create env
        run: mv .env.example .env
      - name: start docker stack
        run: docker compose -f contrib/compose.yaml up -d
      - name: install sqlx
        run: cargo install sqlx-cli
      - name: run migrations
        run: cargo sqlx migrate run
      - name: install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install cargo-docs-rs
        uses: dtolnay/install@cargo-docs-rs
      - name: cargo docs-rs
        run: cargo docs-rs
      - name: stop docker stack
        run: docker compose -f contrib/compose.yaml down -v
  hack:
    runs-on: ubuntu-latest
    name: ubuntu / stable / features
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: create env
        run: mv .env.example .env
      - name: start docker stack
        run: docker compose -f contrib/compose.yaml up -d
      - name: install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: install sqlx
        run: cargo install sqlx-cli
      - name: run migrations
        run: cargo sqlx migrate run
      - name: cargo install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: cargo hack
        run: cargo hack --feature-powerset check
      - name: stop docker stack
        run: docker compose -f contrib/compose.yaml down -v
  msrv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        msrv: ["1.84.1"]
    name: ubuntu / ${{ matrix.msrv }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.msrv }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.msrv }}
      - name: start docker stack
        run: docker compose -f contrib/compose.yaml up -d
      - name: create env
        run: mv .env.example .env
      - name: install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: install sqlx
        run: cargo install sqlx-cli
      - name: run migrations
        run: cargo sqlx migrate run
      - name: cargo +${{ matrix.msrv }} check
        run: cargo check
      - name: stop docker stack
        run: docker compose -f contrib/compose.yaml down -v
